// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKwvusK8HBsenBNamogfhIw2NGwSWr5bs',
    appId: '1:483742956620:web:d171e396c11c6f119dc8e9',
    messagingSenderId: '483742956620',
    projectId: 'supertracker-4e93e',
    authDomain: 'supertracker-4e93e.firebaseapp.com',
    storageBucket: 'supertracker-4e93e.appspot.com',
    measurementId: 'G-4VLMPY4S88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGRncVPChlR8gyEMlXRpXZDcOeY5zf0c8',
    appId: '1:483742956620:android:992f29e1480158449dc8e9',
    messagingSenderId: '483742956620',
    projectId: 'supertracker-4e93e',
    storageBucket: 'supertracker-4e93e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcrVgW_daJ376M4E1VK2J6IRczZFy5yd8',
    appId: '1:483742956620:ios:f7f83f556160dc399dc8e9',
    messagingSenderId: '483742956620',
    projectId: 'supertracker-4e93e',
    storageBucket: 'supertracker-4e93e.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcrVgW_daJ376M4E1VK2J6IRczZFy5yd8',
    appId: '1:483742956620:ios:f7f83f556160dc399dc8e9',
    messagingSenderId: '483742956620',
    projectId: 'supertracker-4e93e',
    storageBucket: 'supertracker-4e93e.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKwvusK8HBsenBNamogfhIw2NGwSWr5bs',
    appId: '1:483742956620:web:48a8774b1d4b66f49dc8e9',
    messagingSenderId: '483742956620',
    projectId: 'supertracker-4e93e',
    authDomain: 'supertracker-4e93e.firebaseapp.com',
    storageBucket: 'supertracker-4e93e.appspot.com',
    measurementId: 'G-EFNFW01HHJ',
  );
}
